jobs:
  include:
    - stage: Tests
      name: "Kourou Lint"
      language: node_js
      node_js: 12
      cache:
        directories:
          - ~/.npm
          - ~/.cache
          - node_modules # NPM packages

      install:
        - npm install --silent --unsafe-perm
        - npm install --silent --unsafe-perm --only=dev

      script:
        - npm run test:lint

    - stage: Tests
      name: "Kourou Functional Stdout Tests"
      language: node_js
      node_js: 12
      cache:
        directories:
          - ~/.npm
          - ~/.cache
          - node_modules # NPM packages

      install:
        - npm install --silent --unsafe-perm
        - npm install --silent --unsafe-perm --only=dev

      script:
        - npm run test:functional:stdout

    - stage: Tests
      name: "Kourou Functional Cucumber Tests"
      language: node_js
      node_js: 12
      cache:
        directories:
          - ~/.npm
          - ~/.cache
          - node_modules # NPM packages

      install:
        - npm install --silent --unsafe-perm
        - npm install --silent --unsafe-perm --only=dev

      script:
        - bash features/run-kuzzle-stack.sh
        - npm run test:functional:cucumber

    - stage: Deploy
      name: Deploy Kourou on NPM
      if: type = push AND branch = master
      sudo: false
      language: node_js
      node_js: 12
      install:
        - npm install
      deploy:
        provider: npm
        skip_cleanup: true
        email: support@kuzzle.io
        api_key:
          secure: "Okjz1ycNqXeoQif4BlnS5ioJZfgOJd977S6le1uQnmtZegVZO5pGiGNkedEV8lbKZFFJ3HB3FlIzkSNU7SUrNH3arycwC6b+P2HK8sZmOuWk6f+ORRVlbxUZ4oJv9o4DYIJK5bc+QG2IL6ItI1yCW00qT39NScP4/Tcr9+H/Ex8aguCWyZuI8aXa1sM3ZAnu8H6ET/w4nWJPM5GeJMe+g6Wq21K+QfE7wBGPzqf+QKH3phChdbYm9JKCRfZ2yhE9N6zwb65MuKIGlCgb3TMBGvy/uMnWbA/L1eaUkY9W0nXTN+PTRwx/yF/60suTPjPN0v1tm16AxV+IA4YfqP97tozgWqiRvhxk3sfs8qJj/H13IiP731hc0uDY83GOhHmHjAfoVRkicSbQ7BTuox6MUX0e0gJZjFwPPML234JLZ54IjVLVc95m0U4ru8/txu5SMBDqQgV6D6x3nk/qOJFDPKeMxhu5K94gSATXoiUhndxOczYjTt3c4hugaE/DQuz1GSLSXbV/z2gG28SY4bpD9y6A1HI4FpGEiZnDNEkCfulLXVPIpV3VgLOF/5StkbDXYrYzpxt5nduPpPxrbuYGmuqioLJoQZyJjieScmMyL1k4E/WPX2tAJn2W7ihnTtIc/gX7K85r1tEYgj60SNEgX7HxkIBwqO2lHMwjmv4fdW8="
        on:
          repo: kuzzleio/kourou
          all_branches: true

